const UUID={service:'00009822-ae15-bc10-5201-856a95fcd178',rx:'00009822-ae15-bc10-5202-856a95fcd178',tx:'00009822-ae15-bc10-5203-856a95fcd178'};
const $=id=>document.getElementById(id), enc=new TextEncoder(), dec=new TextDecoder();
let device,rxChar,txChar,receiveBuffer='',outputOn=false;
const samples=[],MAX_SAMPLES=300;
const ui={connect:$('connectBtn'),status:$('statusText'),dot:$('statusDot'),apply:$('applyBtn'),output:$('outputBtn'),send:$('sendBtn'),term:$('terminal'),empty:$('chartEmpty'),canvas:$('chart')};

function setTheme(theme){const dark=theme==='dark';document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('theme',dark?'dark':'light');const button=$('themeBtn');button.querySelector('span').textContent=dark?'☀':'☾';button.querySelector('b').textContent=dark?'亮色':'暗色';button.setAttribute('aria-label',dark?'切换到亮色主题':'切换到暗色主题');button.title=button.getAttribute('aria-label');document.querySelector('meta[name="theme-color"]').content=dark?'#070b14':'#f4f7fb';drawChart()}

function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function log(type,text){ui.term.querySelector('.hint')?.remove();const row=document.createElement('div');row.className=type;const time=document.createElement('time');time.textContent=new Date().toLocaleTimeString();row.append(time,document.createTextNode(`${type.toUpperCase()}  ${text.replace(/\n$/,'\\n')}`));ui.term.append(row);while(ui.term.children.length>250)ui.term.firstChild.remove();ui.term.scrollTop=ui.term.scrollHeight}
function setConnected(connected){ui.status.textContent=connected?(device?.name||'已连接'):'未连接';ui.dot.style.background=connected?'var(--green)':'var(--red)';ui.dot.style.boxShadow=`0 0 12px ${connected?'var(--green)':'var(--red)'}`;ui.connect.textContent=connected?'断开':'连接设备';[ui.apply,ui.output,ui.send].forEach(x=>x.disabled=!connected)}
async function connect(){if(device?.gatt?.connected){device.gatt.disconnect();return}if(!navigator.bluetooth){toast('当前浏览器不支持 Web Bluetooth');return}try{device=await navigator.bluetooth.requestDevice({acceptAllDevices:true,optionalServices:[UUID.service]});device.addEventListener('gattserverdisconnected',()=>{rxChar=txChar=null;setConnected(false);log('err','BLE 连接已断开')});const server=await device.gatt.connect(),service=await server.getPrimaryService(UUID.service);rxChar=await service.getCharacteristic(UUID.rx);txChar=await service.getCharacteristic(UUID.tx);await txChar.startNotifications();txChar.addEventListener('characteristicvaluechanged',onData);setConnected(true);log('rx',`已连接 ${device.name||device.id}`);toast('BLE 连接成功')}catch(e){log('err',e.message);toast(`连接失败：${e.message}`)}}
async function send(command){if(!rxChar)throw new Error('设备未连接');let frame=command.trim();if(!frame.endsWith('@'))frame+='@';frame+='\n';await rxChar.writeValueWithoutResponse(enc.encode(frame));log('tx',frame)}
function onData(event){const chunk=dec.decode(event.target.value,{stream:true});log('rx',chunk);receiveBuffer+=chunk;let nl;while((nl=receiveBuffer.indexOf('\n'))>=0){const line=receiveBuffer.slice(0,nl);receiveBuffer=receiveBuffer.slice(nl+1);parseLine(line)}}
function withUnit(value,unit){const n=Number(value);if(!Number.isFinite(n))return NaN;const u=unit.toLowerCase();if(u==='mv'||u==='ma'||u==='mw')return n/1000;if(u==='uv'||u==='ua'||u==='uw')return n/1e6;return n}
function parseLine(line){const fields={};for(const item of line.split(',')){const m=item.match(/^([^=]+)=([^@]+)@([^,]*)$/);if(m)fields[m[1]]={value:m[2],unit:m[3]}}const val=k=>fields[k]?withUnit(fields[k].value,fields[k].unit):NaN;const outV=val('o_vol'),outA=val('o_cur'),outW=val('o_pw'),inV=val('i_vol'),inA=val('i_cur');setMetric('outVoltage',outV);setMetric('outCurrent',outA);setMetric('outPower',outW);setMetric('inVoltage',inV);setMetric('inCurrent',inA);if(Number.isFinite(outV)||Number.isFinite(outA)){samples.push({t:Date.now(),v:outV,a:outA});if(samples.length>MAX_SAMPLES)samples.shift();$('sampleCount').textContent=`${samples.length} 个采样点`;ui.empty.style.display='none';drawChart()}}
function setMetric(id,value){if(Number.isFinite(value))$(id).textContent=value.toFixed(3)}

function axisMax(key,fallback){const max=Math.max(0,...samples.map(s=>Number.isFinite(s[key])?s[key]:0));return max?Math.ceil(max*11.5)/10:fallback}
console.assert(axisMax('v',1)===1,'empty chart scale');samples.push({v:5});console.assert(axisMax('v',1)===5.8,'dynamic chart scale');samples.pop();
function drawChart(){const canvas=ui.canvas,dpr=devicePixelRatio||1,rect=canvas.getBoundingClientRect(),style=getComputedStyle(document.documentElement),vMax=axisMax('v',1),aMax=axisMax('a',.1);canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const w=rect.width,h=rect.height,p={l:46,r:46,t:14,b:28},cw=w-p.l-p.r,ch=h-p.t-p.b;c.strokeStyle=style.getPropertyValue('--chart-grid');c.fillStyle=style.getPropertyValue('--chart-label');c.font='10px Segoe UI';c.lineWidth=1;for(let i=0;i<=4;i++){const y=p.t+ch*i/4;c.beginPath();c.moveTo(p.l,y);c.lineTo(w-p.r,y);c.stroke();c.fillText(`${(vMax*(4-i)/4).toFixed(vMax<10?2:1)}V`,4,y+3);c.fillText(`${(aMax*(4-i)/4).toFixed(aMax<10?2:1)}A`,w-p.r+8,y+3)}if(samples.length<2)return;const plot=(key,max,color)=>{c.strokeStyle=color;c.lineWidth=2;c.beginPath();samples.forEach((s,i)=>{const x=p.l+cw*i/(MAX_SAMPLES-1),y=p.t+ch*(1-Math.max(0,Math.min(max,s[key]||0))/max);i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()};plot('v',vMax,style.getPropertyValue('--cyan-bright'));plot('a',aMax,style.getPropertyValue('--amber'))}

ui.connect.addEventListener('click',connect);
$('themeBtn').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
$('settingsForm').addEventListener('submit',async e=>{e.preventDefault();const v=Number($('voltageInput').value),a=Number($('currentInput').value);if(v<2||v>34||a<.01||a>8)return toast('设置值超出固件允许范围');try{await send(`o_cfg=${v.toFixed(3)}@c_cfg=${a.toFixed(3)}@`);toast('输出设置已发送')}catch(err){toast(err.message)}});
ui.output.addEventListener('click',async()=>{try{const next=!outputOn;await send(`o_ctr=${next?1:0}`);outputOn=next;ui.output.classList.toggle('on',next);ui.output.querySelector('span').textContent=next?'输出开启':'输出关闭'}catch(e){toast(e.message)}});
const quickInputs=[...document.querySelectorAll('.quick-voltage')],savedQuick=localStorage.getItem('quickVoltages')?.split(',');
if(savedQuick)quickInputs.forEach((input,i)=>input.value=savedQuick[i]??input.value);
quickInputs.forEach(input=>input.nextElementSibling.addEventListener('click',()=>{if(!input.reportValidity())return;$('voltageInput').value=Number(input.value).toFixed(3);localStorage.setItem('quickVoltages',quickInputs.map(x=>x.value).join(','))}));
$('rawForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('rawInput');if(!input.value.trim())return;try{await send(input.value);input.value=''}catch(err){toast(err.message)}});
$('clearLog').onclick=()=>ui.term.innerHTML='<div class="hint">日志已清空</div>';
$('clearChart').onclick=()=>{samples.length=0;$('sampleCount').textContent='0 个采样点';ui.empty.style.display='grid';drawChart()};
addEventListener('resize',drawChart);setConnected(false);setTheme(localStorage.getItem('theme')==='dark'?'dark':'light');
